-- Run in Supabase SQL Editor
ALTER TABLE matches ADD COLUMN IF NOT EXISTS league_code TEXT;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS sd_match_id INTEGER;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS excitement_rating NUMERIC;
ALTER TABLE match_scores ADD COLUMN IF NOT EXISTS factors JSONB;