ALTER TABLE matches ADD COLUMN IF NOT EXISTS home_score INTEGER;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS away_score INTEGER;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS home_ht_score INTEGER;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS away_ht_score INTEGER;