'use client'
export default function TermsPage() {
  const s = { marginBottom: '20px' }
  const h2 = { fontSize: '16px', fontWeight: 700, marginBottom: '8px', marginTop: '28px', color: 'var(--text)' }
  const p = { color: 'var(--text-secondary)', fontSize: '14px', lineHeight: '1.7' }
  const li = { color: 'var(--text-secondary)', fontSize: '14px', lineHeight: '1.7', marginBottom: '6px' }
  return (
    <div style={{ maxWidth: '720px', margin: '0 auto', paddingBottom: '60px' }}>
      <h1 style={{ fontSize: '26px', fontWeight: 800, marginBottom: '8px', marginTop: '32px' }}>Terms and Conditions</h1>
      <p style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '32px' }}>Last updated: May 2026. Please read these terms carefully before using MatchEdge.</p>

      <div style={{ background: 'var(--card)', border: '1px solid #f59e0b40', borderRadius: '8px', padding: '16px 18px', marginBottom: '28px' }}>
        <p style={{ color: '#f59e0b', fontSize: '14px', fontWeight: 600, marginBottom: '6px' }}>Important Notice</p>
        <p style={{ color: 'var(--text-secondary)', fontSize: '13px', lineHeight: '1.7' }}>MatchEdge is a football analysis and tipping information service. We do not accept bets, operate as a bookmaker, or provide regulated financial advice. Our content is for information and entertainment purposes only. You must be 18 or over to use this service.</p>
      </div>

      <h2 style={h2}>1. About MatchEdge</h2>
      <p style={p}>MatchEdge (referred to as the Service, we, us, or our) is operated as a football analytics and tipster information platform. The Service provides data-driven match analysis, AI-generated tipster picks, and historical performance tracking across English Premier League and Scottish Premiership fixtures.</p>
      <p style={{ ...p, marginTop: '10px' }}>MatchEdge is not a licensed bookmaker, betting exchange, or gambling operator. We do not accept wagers or process bets of any kind. All tips, predictions, and analysis published on the platform are provided for information and entertainment purposes only and do not constitute financial, investment, or betting advice.</p>

      <h2 style={h2}>2. Eligibility</h2>
      <p style={p}>You must meet all of the following criteria to use MatchEdge:</p>
      <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
        <li style={li}>You are at least 18 years of age.</li>
        <li style={li}>You are accessing the Service from a jurisdiction where online gambling information services are lawful.</li>
        <li style={li}>You have read and accept these Terms and Conditions in full.</li>
        <li style={li}>You acknowledge that gambling involves risk and that past performance of our tipsters is not indicative of future results.</li>
      </ul>
      <p style={{ ...p, marginTop: '10px' }}>We reserve the right to terminate access for any user we believe to be under 18 or in breach of these terms.</p>

      <h2 style={h2}>3. Responsible Gambling</h2>
      <p style={p}>MatchEdge takes responsible gambling seriously. We include BeGambleAware messaging throughout our platform and require all users to confirm they are 18 or over and to acknowledge the risks of gambling at the point of registration.</p>
      <p style={{ ...p, marginTop: '10px' }}>If you or someone you know is experiencing harm from gambling, please seek help immediately:</p>
      <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
        <li style={li}>BeGambleAware: www.begambleaware.org | 0808 8020 133 (free, 24/7)</li>
        <li style={li}>GamCare: www.gamcare.org.uk | 0808 8020 133</li>
        <li style={li}>Gambling Therapy: www.gamblingtherapy.org</li>
        <li style={li}>Gordon Moody: www.gordonmoody.org.uk</li>
      </ul>
      <p style={{ ...p, marginTop: '10px' }}>We encourage all users to set personal deposit limits and use self-exclusion tools provided by licensed bookmakers. MatchEdge is not responsible for any gambling decisions made by users based on content published on this platform.</p>

      <h2 style={h2}>4. Nature of Tips and Analysis</h2>
      <p style={p}>All tips, predictions, scores, and analysis published on MatchEdge are generated by automated systems and AI models. They are provided for entertainment and informational purposes only. The following apply at all times:</p>
      <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
        <li style={li}>Tips are not guaranteed to be accurate or profitable.</li>
        <li style={li}>Historical win rates and P+L figures reflect past performance only and are not a reliable indicator of future results.</li>
        <li style={li}>You should never bet more than you can afford to lose.</li>
        <li style={li}>MatchEdge accepts no liability for financial losses incurred by users acting on content published on the platform.</li>
        <li style={li}>Odds shown are indicative only and may differ from those available at bookmakers at time of betting.</li>
      </ul>

      <h2 style={h2}>5. Subscriptions and Payments</h2>
      <p style={p}>MatchEdge offers the following subscription tiers:</p>
      <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
        <li style={li}><strong style={{ color: 'var(--text)' }}>Free:</strong> Limited access at no cost. No payment required.</li>
        <li style={li}><strong style={{ color: '#4d9fff' }}>Pro (£9.99/month):</strong> Full match analysis and 30 days tipster history.</li>
        <li style={li}><strong style={{ color: 'var(--gold)' }}>Edge (£24.99/month):</strong> All Pro features plus live refresh, full history, and admin access.</li>
        <li style={li}><strong style={{ color: 'var(--gold)' }}>Day Pass (£1.99):</strong> Full Edge access until midnight on the day of purchase.</li>
      </ul>
      <p style={{ ...p, marginTop: '10px' }}>Subscriptions are billed monthly in advance. You may cancel at any time. Cancellation takes effect at the end of the current billing period. No refunds are issued for partial months. Payments are processed securely by Stripe. We do not store card details.</p>
      <p style={{ ...p, marginTop: '10px' }}>Day passes expire at midnight UK time on the day of purchase and do not auto-renew. No refunds are available on day passes once purchased.</p>

      <h2 style={h2}>6. Intellectual Property</h2>
      <p style={p}>All content on MatchEdge, including but not limited to scoring models, tipster personas, AI-generated text, interface design, and historical data, is the intellectual property of MatchEdge and its operators. You may not reproduce, redistribute, or commercially exploit any content from the platform without express written permission.</p>

      <h2 style={h2}>7. Prohibited Use</h2>
      <p style={p}>You agree not to use MatchEdge for any of the following:</p>
      <ul style={{ paddingLeft: '20px', marginTop: '8px' }}>
        <li style={li}>Scraping, harvesting, or automated extraction of data or tips for commercial redistribution.</li>
        <li style={li}>Sharing subscription credentials with third parties.</li>
        <li style={li}>Any activity that violates applicable law or regulation.</li>
        <li style={li}>Attempting to circumvent plan restrictions or access controls.</li>
      </ul>

      <h2 style={h2}>8. Disclaimers and Limitation of Liability</h2>
      <p style={p}>The Service is provided on an as-is and as-available basis. MatchEdge makes no warranties, express or implied, regarding the accuracy, reliability, or fitness for purpose of any content on the platform.</p>
      <p style={{ ...p, marginTop: '10px' }}>To the fullest extent permitted by law, MatchEdge and its operators shall not be liable for any direct, indirect, incidental, or consequential loss or damage arising from use of the platform, including but not limited to financial losses resulting from betting decisions.</p>

      <h2 style={h2}>9. Affiliate Links</h2>
      <p style={p}>MatchEdge displays links to licensed bookmakers. These links may be affiliate links, meaning we may receive a commission if you register and deposit with a bookmaker via our link. This does not affect the odds or offers available to you. We only link to bookmakers licensed by the UK Gambling Commission. You should always gamble responsibly and within your means.</p>

      <h2 style={h2}>10. Changes to These Terms</h2>
      <p style={p}>We reserve the right to update these Terms and Conditions at any time. We will notify registered users of material changes by email. Continued use of the platform following notification constitutes acceptance of the revised terms.</p>

      <h2 style={h2}>11. Governing Law</h2>
      <p style={p}>These Terms and Conditions are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>

      <h2 style={h2}>12. Contact</h2>
      <p style={p}>For any questions regarding these Terms and Conditions, please contact us at the email address registered on your account or via the contact details published on the platform.</p>

      <div style={{ marginTop: '40px', padding: '16px', background: 'var(--card)', borderRadius: '8px', fontSize: '12px', color: 'var(--text-muted)', textAlign: 'center', lineHeight: '1.8' }}>
        18+ only. MatchEdge does not accept bets. For information and entertainment only.<br />
        <a href='https://www.begambleaware.org' target='_blank' rel='noopener noreferrer' style={{ color: 'var(--text-muted)' }}>BeGambleAware.org</a> | 0808 8020 133 (free, 24/7)
      </div>
    </div>
  )
}